using System.Text.Json;using Essco.Application.Customers;using Essco.Domain;using Essco.Domain.Returns;using Essco.SapBridge.Contracts;
namespace Essco.Application.Returns;
public static class ReturnSapOperations{public const string CreateCreditNote="Return.CreateCreditNote";}public sealed record ReturnSapPayload(int Number);
public interface IReturnRepository{ValueTask<IReadOnlyCollection<ReturnRequest>>ListAsync(ReturnFilter filter,CancellationToken token);ValueTask<ReturnRequest?>GetAsync(int number,CancellationToken token);ValueTask<bool>MarkProcessedAsync(int number,int sapEntry,CancellationToken token);}
public sealed class ReturnService(IReturnRepository repository,ISapJobQueue queue)
{public ValueTask<IReadOnlyCollection<ReturnRequest>>ListAsync(ReturnFilter f,CancellationToken t)=>repository.ListAsync(f,t);public ValueTask<ReturnRequest?>GetAsync(int n,CancellationToken t)=>repository.GetAsync(n,t);public async ValueTask<(bool Succeeded,SapJob?Job,string?Error)>DispatchAsync(int n,string company,string user,CancellationToken t){var x=await repository.GetAsync(n,t);if(x is null)return(false,null,"La devolución no existe.");if(x.Processed)return(false,null,"La devolución ya fue procesada.");if(x.Lines.Count==0)return(false,null,"La devolución no contiene líneas.");var job=await queue.EnqueueAsync(new(ReturnSapOperations.CreateCreditNote,company,user,JsonSerializer.Serialize(new ReturnSapPayload(n)),$"return:{n}:credit-note"),t);return(true,job,null);}}
public interface ISapReturnGateway{ValueTask<SapProcessingResult>CreateCreditNoteAsync(ReturnRequest request,CancellationToken token);}public interface IReturnSapJobProcessor{ValueTask<SapProcessingResult>ProcessAsync(string operation,string payload,CancellationToken token);}
public sealed class ReturnSapJobProcessor(IReturnRepository repository,ISapReturnGateway gateway):IReturnSapJobProcessor
{public async ValueTask<SapProcessingResult>ProcessAsync(string operation,string payload,CancellationToken t){if(operation!=ReturnSapOperations.CreateCreditNote)return new(false,null,"Operación de devolución no soportada.",false);ReturnSapPayload? p;try{p=JsonSerializer.Deserialize<ReturnSapPayload>(payload);}catch(JsonException){return new(false,null,"Payload de devolución inválido.",false);}if(p is null)return new(false,null,"Payload vacío.",false);var x=await repository.GetAsync(p.Number,t);if(x is null)return new(false,null,"La devolución ya no existe.",false);if(x.Processed)return new(true,x.SapDocumentEntry?.ToString()??x.Number.ToString(),null,false);var result=await gateway.CreateCreditNoteAsync(x,t);if(!result.Succeeded)return result;if(!int.TryParse(result.ExternalId,out var entry))return new(false,result.ExternalId,"SAP creó la nota pero no devolvió un DocEntry válido; requiere conciliación manual.",false);return await repository.MarkProcessedAsync(x.Number,entry,t)?result:new(false,result.ExternalId,"SAP creó la nota pero SQL no pudo marcarla; requiere conciliación manual.",false);}}
