using Essco.Application;
using Essco.Application.Customers;
using Essco.Application.Purchasing;
using Essco.Domain;
using Essco.Domain.Purchasing;
using Essco.SapBridge.Contracts;
namespace Essco.Tests.Unit.Purchasing;

public sealed class PurchaseOrderTests
{ [Fact] public async Task Dispatch_is_idempotent_by_order_number() { var q = new Queue(); var r = await new PurchaseOrderService(new Repo(), q).DispatchAsync(7, "E", "u", default); Assert.True(r.Succeeded); Assert.Equal("purchase-order:7:create", q.Request!.IdempotencyKey); } [Fact] public async Task Processor_confirms_order_after_sap() { var repo = new Repo(); var r = await new PurchaseOrderSapJobProcessor(repo, new Gateway()).ProcessAsync(PurchaseOrderSapOperations.Create, "{\"number\":7}", default); Assert.True(r.Succeeded); Assert.True(repo.Marked); } private sealed class Repo : IPurchaseOrderRepository { public bool Marked { get; private set; } public ValueTask<IReadOnlyCollection<PurchaseOrder>> ListAsync(PurchaseOrderFilter f, CancellationToken t) => ValueTask.FromResult<IReadOnlyCollection<PurchaseOrder>>([]); public ValueTask<PurchaseOrder?> GetAsync(int n, CancellationToken t) => ValueTask.FromResult<PurchaseOrder?>(new(n, new(2026, 1, 1), "P1", "Proveedor", false, false, [new(1, "A", "Artículo", 10, 1, 2, 2, 20, true, "")])); public ValueTask<bool> UpdateLineAsync(int n, PurchaseOrderLine l, CancellationToken t) => ValueTask.FromResult(true); public ValueTask<bool> CancelAsync(int n, CancellationToken t) => ValueTask.FromResult(true); public ValueTask<bool> MarkCreatedAsync(int n, int e, CancellationToken t) { Marked = true; return ValueTask.FromResult(true); } } private sealed class Gateway : ISapPurchaseOrderGateway { public ValueTask<SapProcessingResult> CreateAsync(PurchaseOrder o, CancellationToken t) => ValueTask.FromResult(new SapProcessingResult(true, "123", null, false)); } private sealed class Queue : ISapJobQueue { public CreateSapJobRequest? Request { get; private set; } public ValueTask<SapJob> EnqueueAsync(CreateSapJobRequest r, CancellationToken t) { Request = r; return ValueTask.FromResult(new SapJob { OperationType = r.OperationType, Company = r.Company, RequestedBy = r.RequestedBy, Payload = r.Payload }); } public ValueTask<SapJob?> ClaimNextAsync(CancellationToken t) => ValueTask.FromResult<SapJob?>(null); public ValueTask CompleteAsync(Guid i, string e, CancellationToken t) => ValueTask.CompletedTask; public ValueTask FailAsync(Guid i, string e, bool r, CancellationToken t) => ValueTask.CompletedTask; public ValueTask<IReadOnlyCollection<SapJob>> GetSnapshotAsync(CancellationToken t) => ValueTask.FromResult<IReadOnlyCollection<SapJob>>([]); } }
