using System.Runtime.InteropServices;
using Essco.Application.Configuration;
using Essco.Application.Purchasing;
using Essco.Application.Customers;
using Essco.Domain.Purchasing;
using Microsoft.Extensions.Options;
namespace Essco.SapBridge.Worker;

public sealed class ComSapPurchaseOrderGateway(IOptions<EsscoOptions> options, ILogger<ComSapPurchaseOrderGateway> logger) : ISapPurchaseOrderGateway
{
    public ValueTask<SapProcessingResult> CreateAsync(PurchaseOrder order, CancellationToken token) { token.ThrowIfCancellationRequested(); if (!options.Value.Sap.Enabled) return ValueTask.FromResult(new SapProcessingResult(false, null, "La conexión SAP no está habilitada.", false)); var done = new TaskCompletionSource<SapProcessingResult>(TaskCreationOptions.RunContinuationsAsynchronously); var thread = new Thread(() => { try { done.TrySetResult(Create(order)); } catch (COMException ex) { logger.LogWarning("Error COM SAP {Code} procesando pedido {Order}", ex.ErrorCode, order.Number); done.TrySetResult(new(false, null, $"Error COM SAP ({ex.ErrorCode}).", true)); } catch (Exception ex) { logger.LogError(ex, "Error procesando pedido {Order}", order.Number); done.TrySetResult(new(false, null, "Error interno del adaptador SAP.", true)); } }) { IsBackground = true, Name = "Essco SAP DI API Purchase Order" }; thread.SetApartmentState(ApartmentState.STA); thread.Start(); return new(done.Task); }
    private SapProcessingResult Create(PurchaseOrder x) { dynamic? company = null; dynamic? order = null; try { var type = Type.GetTypeFromProgID("SAPbobsCOM.Company") ?? throw new COMException("SAP DI API no está registrada."); company = Activator.CreateInstance(type) ?? throw new COMException("No fue posible crear Company."); var c = options.Value.Sap; company.Server = c.Server; company.CompanyDB = c.CompanyDatabase; company.UserName = c.UserName; company.Password = c.Password; company.DbUserName = c.DatabaseUserName; company.DbPassword = c.DatabasePassword; company.LicenseServer = c.LicenseServer; company.DbServerType = c.DatabaseServerType; company.UseTrusted = false; var connected = (int)company.Connect(); if (connected != 0) return Failure(company, connected, true); order = company.GetBusinessObject(22); order.CardCode = x.SupplierCode; order.DocDate = x.Date.ToDateTime(TimeOnly.MinValue); order.DocDueDate = x.Date.ToDateTime(TimeOnly.MinValue); order.NumAtCard = x.Number.ToString(System.Globalization.CultureInfo.InvariantCulture); order.Comments = $"Pedido Essco {x.Number}"; var lines = x.Lines.Where(l => l.Units > 0).ToArray(); for (var i = 0; i < lines.Length; i++) { var line = lines[i]; if (i > 0) order.Lines.Add(); order.Lines.ItemCode = line.ItemCode; order.Lines.Quantity = (double)line.Units; order.Lines.UnitPrice = (double)line.Cost; order.Lines.FreeText = line.Reason; } var added = (int)order.Add(); if (added != 0) return Failure(company, added, false); return new(true, Convert.ToString(company.GetNewObjectKey()), null, false); } finally { Release(order); try { if (company is not null && (bool)company.Connected) company.Disconnect(); } catch (COMException) { } Release(company); } }
    private static SapProcessingResult Failure(dynamic c, int code, bool retry) { string m = ""; try { c.GetLastError(out code, out m); } catch (COMException) { } return new(false, null, $"SAP rechazó la operación ({code}): {m}", retry); }
    private static void Release(object? x) { if (x is not null && Marshal.IsComObject(x)) Marshal.FinalReleaseComObject(x); }
}
