using System.ComponentModel.DataAnnotations;using System.Globalization;using System.Security.Claims;using Essco.Application.Auditing;using Essco.Application.Configuration;using Essco.Application.Liquidations;using Essco.Application.Security;using Essco.Domain.Liquidations;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Mvc.RazorPages;using Microsoft.Extensions.Options;
namespace Essco.Web.Pages.Liquidations;
[Authorize(Policy=Permissions.LiquidationDifferences)]
public sealed class IndexModel(LiquidationService service,AuditService audit,IOptions<EsscoOptions> options):PageModel
{
 [BindProperty(SupportsGet=true)]public FilterModel Filter{get;set;}=new();[BindProperty]public InputModel Input{get;set;}=new();public IReadOnlyCollection<Liquidation> Items{get;private set;}=[];[TempData]public string? StatusMessage{get;set;}
 public async Task OnGetAsync(int? edit,CancellationToken token){await Load(token);if(edit is not null){var x=Items.SingleOrDefault(x=>x.Consecutive==edit);if(x is not null)Input=InputModel.FromEntity(x);}}
 public async Task<IActionResult> OnPostSaveAsync(CancellationToken token){if(ModelState.IsValid){var result=await service.SaveAsync(Input.Domain(),Input.IsNew,token);if(result.Succeeded){await Log("liquidation.save",result.Consecutive,"Succeeded",token);StatusMessage=$"Liquidación {result.Consecutive} guardada.";return RedirectToPage(Filter.Route());}ModelState.AddModelError("",result.Error??"No fue posible guardar.");}await Load(token);return Page();}
 public async Task<IActionResult> OnPostAnnulAsync(int consecutive,string type,CancellationToken token){var ok=await service.AnnulAsync(Filter.Kind,consecutive,type,token);await Log("liquidation.annul",consecutive,ok?"Succeeded":"Rejected",token);StatusMessage=ok?$"Liquidación {consecutive} anulada.":"No fue posible anular.";return RedirectToPage(Filter.Route());}
 private async Task Load(CancellationToken token)=>Items=await service.ListAsync(Filter.Domain(),token);
 private async Task Log(string operation,int id,string result,CancellationToken token){var userId=int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),NumberStyles.None,CultureInfo.InvariantCulture,out var p)?p:(int?)null;await audit.WriteAsync(userId,User.Identity?.Name??"",options.Value.DefaultCompany,operation,Filter.Kind.ToString(),id.ToString(CultureInfo.InvariantCulture),result,HttpContext.TraceIdentifier,HttpContext.Connection.RemoteIpAddress?.ToString(),token);}
 public sealed class FilterModel{public LiquidationKind Kind{get;set;}=LiquidationKind.Agents;[DataType(DataType.Date)]public DateOnly? From{get;set;}[DataType(DataType.Date)]public DateOnly? To{get;set;}public int? Consecutive{get;set;}public bool IncludeAnnulled{get;set;}public LiquidationFilter Domain()=>new(Kind,From,To,Consecutive,IncludeAnnulled);public IReadOnlyDictionary<string,object?>Route()=>new Dictionary<string,object?>{{"Filter.Kind",Kind},{"Filter.From",From},{"Filter.To",To},{"Filter.Consecutive",Consecutive},{"Filter.IncludeAnnulled",IncludeAnnulled}};}
 public sealed class InputModel
 {public bool IsNew{get;set;}=true;public int Consecutive{get;set;}public LiquidationKind Kind{get;set;}=LiquidationKind.Agents;[Required]public string EmployeeCode{get;set;}="";public string Identification{get;set;}="";[Required]public string EmployeeName{get;set;}="";[DataType(DataType.Date)]public DateOnly Date{get;set;}=DateOnly.FromDateTime(DateTime.Today);[DataType(DataType.Date)]public DateOnly From{get;set;}=DateOnly.FromDateTime(DateTime.Today);[DataType(DataType.Date)]public DateOnly To{get;set;}=DateOnly.FromDateTime(DateTime.Today);[DataType(DataType.Date)]public DateOnly ReceiptFrom{get;set;}=DateOnly.FromDateTime(DateTime.Today);[DataType(DataType.Date)]public DateOnly ReceiptTo{get;set;}=DateOnly.FromDateTime(DateTime.Today);public string Notes{get;set;}="";[Required]public string Type{get;set;}="AGENTES";public decimal Result{get;set;}public string Route{get;set;}="";public string AgentCodes{get;set;}="";public string InvoiceReportCodes{get;set;}="";
 public Liquidation Domain()=>new(){Consecutive=Consecutive,Kind=Kind,EmployeeCode=EmployeeCode,Identification=Identification,EmployeeName=EmployeeName,Date=Date,From=From,To=To,ReceiptFrom=ReceiptFrom,ReceiptTo=ReceiptTo,Notes=Notes,Type=Type,Result=Result,Route=Route,AgentCodes=AgentCodes,InvoiceReportCodes=InvoiceReportCodes};public static InputModel FromEntity(Liquidation x)=>new(){IsNew=false,Consecutive=x.Consecutive,Kind=x.Kind,EmployeeCode=x.EmployeeCode,Identification=x.Identification,EmployeeName=x.EmployeeName,Date=x.Date,From=x.From,To=x.To,ReceiptFrom=x.ReceiptFrom,ReceiptTo=x.ReceiptTo,Notes=x.Notes,Type=x.Type,Result=x.Result,Route=x.Route,AgentCodes=x.AgentCodes,InvoiceReportCodes=x.InvoiceReportCodes};}
}
