using System.ComponentModel.DataAnnotations;using System.Globalization;using System.Security.Claims;using Essco.Application.Auditing;using Essco.Application.Configuration;using Essco.Application.HumanResources;using Essco.Application.Security;using Microsoft.AspNetCore.Authorization;using Microsoft.AspNetCore.Mvc;using Microsoft.AspNetCore.Mvc.RazorPages;using Microsoft.Extensions.Options;
namespace Essco.Web.Pages.Employees;
[Authorize(Policy=Permissions.EmployeesManage)]public sealed class EditModel(EmployeeService service,AuditService audit,IOptions<EsscoOptions> options):PageModel
{
 private const int MaxPhotoBytes=5*1024*1024;
 [BindProperty]public Form Input{get;set;}=new();[BindProperty]public string?OriginalIdentification{get;set;}[BindProperty]public IFormFile?Photo{get;set;}public bool IsNew=>string.IsNullOrWhiteSpace(OriginalIdentification);public IReadOnlyList<string>Positions=>EmployeeCatalog.Positions;public IReadOnlyList<string>Categories=>EmployeeCatalog.Categories;public(int Years,int Months,int Days)Tenure=>EmployeeService.CalculateTenure(Input.HireDate,DateOnly.FromDateTime(DateTime.Today));
 public async Task<IActionResult>OnGetAsync(string?id,CancellationToken t){if(string.IsNullOrWhiteSpace(id)){Input.HireDate=DateOnly.FromDateTime(DateTime.Today);Input.Active=true;return Page();}var file=await service.GetAsync(id,t);if(file is null)return NotFound();var e=file.Employee;OriginalIdentification=e.Identification;Input=new(){Identification=e.Identification,Code=e.Code,Name=e.Name,Position=e.Position,Salary=e.Salary,HireDate=e.HireDate,Active=e.Active,Route=e.Route,Email=e.Email,Phone1=e.Phone1,Phone2=e.Phone2,BankAccount=e.BankAccount,CollaboratorId=e.CollaboratorId,LedgerAccount=e.LedgerAccount,Category=e.Category,VacationEarned=e.VacationEarned,VacationUsed=e.VacationUsed,VacationPending=e.VacationPending};return Page();}
 public async Task<IActionResult>OnGetPhotoAsync(string id,CancellationToken t){var photo=await service.GetPhotoAsync(id,t);if(photo is not {Length:>0})return NotFound();var type=photo.Length>8&&photo[0]==0x89&&photo[1]==0x50?"image/png":photo.Length>12&&photo[8]==0x57&&photo[9]==0x45?"image/webp":"image/jpeg";return File(photo,type);}
 public async Task<IActionResult>OnPostAsync(CancellationToken t){byte[]?photo=null;if(Photo is not null){if(Photo.Length>MaxPhotoBytes)ModelState.AddModelError(nameof(Photo),"La fotografía no puede superar 5 MB.");if(!new[]{"image/jpeg","image/png","image/webp"}.Contains(Photo.ContentType,StringComparer.OrdinalIgnoreCase))ModelState.AddModelError(nameof(Photo),"La fotografía debe ser JPG, PNG o WEBP.");if(ModelState.IsValid){await using var stream=new MemoryStream();await Photo.CopyToAsync(stream,t);photo=stream.ToArray();}}if(!ModelState.IsValid)return Page();var f=Input;var result=await service.SaveAsync(OriginalIdentification,new(f.Identification??"",f.Code??"",f.Name??"",f.Position??"",f.Salary,f.HireDate,f.Active,f.Route??"",f.Email??"",f.Phone1??"",f.Phone2??"",f.BankAccount??"",f.CollaboratorId??"",f.LedgerAccount??"",f.Category??"",f.VacationEarned,f.VacationUsed,f.VacationPending,photo),t);if(!result.Succeeded){ModelState.AddModelError("",result.Error!);await Log("Employee.Save",f.Identification??"","Rejected",t);return Page();}await Log(IsNew?"Employee.Create":"Employee.Update",f.Identification??"","Succeeded",t);return RedirectToPage("Detail",new{id=f.Identification});}
 public async Task<IActionResult>OnPostDeactivateAsync(CancellationToken t){if(string.IsNullOrWhiteSpace(OriginalIdentification))return BadRequest();var result=await service.SetActiveAsync(OriginalIdentification,false,t);await Log("Employee.Deactivate",OriginalIdentification,result.Succeeded?"Succeeded":"Rejected",t);if(!result.Succeeded){ModelState.AddModelError("",result.Error!);return await OnGetAsync(OriginalIdentification,t);}return RedirectToPage("Index");}
 private ValueTask Log(string operation,string key,string result,CancellationToken token){var userId=int.TryParse(User.FindFirstValue(ClaimTypes.NameIdentifier),NumberStyles.None,CultureInfo.InvariantCulture,out var parsed)?parsed:(int?)null;return audit.WriteAsync(userId,User.Identity?.Name??"",options.Value.DefaultCompany,operation,"Empleado",key,result,HttpContext.TraceIdentifier,HttpContext.Connection.RemoteIpAddress?.ToString(),token);}
 public sealed class Form{[Required,Display(Name="Cédula")]public string?Identification{get;set;}[Display(Name="Código cliente SAP"),StringLength(15)]public string?Code{get;set;}[Required,Display(Name="Nombre completo")]public string?Name{get;set;}[Required,Display(Name="Puesto")]public string?Position{get;set;}[Range(1000,double.MaxValue,ErrorMessage="Debe indicar un salario de al menos 1000."),Display(Name="Salario mensual")]public decimal Salary{get;set;}[Display(Name="Fecha de ingreso")]public DateOnly HireDate{get;set;}[Display(Name="Activo")]public bool Active{get;set;}[Display(Name="Ruta")]public string?Route{get;set;}[EmailAddress,Display(Name="Correo electrónico")]public string?Email{get;set;}[Display(Name="Teléfono principal")]public string?Phone1{get;set;}[Display(Name="Teléfono alterno")]public string?Phone2{get;set;}[Required,Display(Name="Cuenta bancaria")]public string?BankAccount{get;set;}[Required,Display(Name="Id. colaborador")]public string?CollaboratorId{get;set;}[StringLength(15),Display(Name="Cuenta contable SAP")]public string?LedgerAccount{get;set;}[Required,Display(Name="Categoría")]public string?Category{get;set;}[Range(0,double.MaxValue),Display(Name="Ganadas")]public decimal VacationEarned{get;set;}[Range(0,double.MaxValue),Display(Name="Consumidas")]public decimal VacationUsed{get;set;}[Range(0,double.MaxValue),Display(Name="Pendientes")]public decimal VacationPending{get;set;}}
}
