using Essco.Application.HumanResources;using Essco.Domain.HumanResources;namespace Essco.Tests.Unit.HumanResources;
public sealed class EmployeeTests
{
 [Fact]public void Accepts_legacy_position_and_category()=>Assert.Empty(Valid().Validate());
 [Fact]public void Rejects_required_and_conditional_fields(){var errors=(Valid()with{Identification="",Name="",Category="",BankAccount="",CollaboratorId="",Position="Agente",Route=""}).Validate();Assert.Contains(errors,x=>x.Field=="Identification");Assert.Contains(errors,x=>x.Field=="Route");Assert.Contains(errors,x=>x.Field=="BankAccount");}
 [Fact]public void Rejects_salary_below_legacy_minimum()=>Assert.Contains((Valid()with{Salary=999}).Validate(),x=>x.Field=="Salary");
 [Fact]public void Legacy_accepts_zero_collaborator_id_because_it_only_requires_content()=>Assert.DoesNotContain((Valid()with{CollaboratorId="0"}).Validate(),x=>x.Field=="CollaboratorId");
 [Fact]public async Task Duplicate_active_has_explicit_message(){var r=new Repo{Duplicate=new("1","",0)};var result=await new EmployeeService(r).SaveAsync(null,Valid(),default);Assert.False(result.Succeeded);Assert.Contains("ACTIVO",result.Error);Assert.False(r.Saved);}
 [Fact]public async Task Duplicate_inactive_has_explicit_message(){var r=new Repo{Duplicate=new("1","",1)};var result=await new EmployeeService(r).SaveAsync(null,Valid(),default);Assert.False(result.Succeeded);Assert.Contains("INACTIVO",result.Error);Assert.Contains("no debe volver",result.Error,StringComparison.OrdinalIgnoreCase);}
 [Fact]public async Task Inactivation_is_allowed_only_from_active(){var r=new Repo{Current=Employee(0)};Assert.True((await new EmployeeService(r).InactivateAsync("1",default)).Succeeded);r.Current=Employee(1);var result=await new EmployeeService(r).InactivateAsync("1",default);Assert.False(result.Succeeded);Assert.Contains("INACTIVO",result.Error);}
 [Fact]public async Task Reactivation_is_allowed_only_from_inactive(){var r=new Repo{Current=Employee(1)};Assert.True((await new EmployeeService(r).ReactivateAsync("1",new(2026,1,1),default)).Succeeded);Assert.Equal(new DateOnly(2026,1,1),r.ReactivationDate);r.Current=Employee(0);Assert.False((await new EmployeeService(r).ReactivateAsync("1",new(2026,1,1),default)).Succeeded);}
 [Fact]public async Task Reactivation_rejects_future_hire_date(){var r=new Repo{Current=Employee(1)};var result=await new EmployeeService(r).ReactivateAsync("1",DateOnly.FromDateTime(DateTime.Today).AddDays(1),default);Assert.False(result.Succeeded);Assert.Null(r.ReactivationDate);}
 [Theory][InlineData(2,"CERRADO")][InlineData(3,"LIQUIDADO")]public async Task Terminal_states_cannot_be_edited_or_inactivated(int state,string name){var r=new Repo{Current=Employee(state)};var service=new EmployeeService(r);Assert.Contains(name,(await service.SaveAsync("1",Valid(),default)).Error);Assert.Contains(name,(await service.InactivateAsync("1",default)).Error);}
 [Fact]public async Task Empty_sap_fields_do_not_require_external_validation(){var r=new Repo{SapLedger=new(ExternalValidationStatus.Unavailable),SapCustomer=new(ExternalValidationStatus.Unavailable)};Assert.True((await new EmployeeService(r).SaveAsync(null,Valid(),default)).Succeeded);}
 [Theory][InlineData("0")][InlineData("999-NO-EXISTE")]public async Task Invalid_sap_account_is_rejected(string account){var r=new Repo{SapLedger=new(ExternalValidationStatus.Invalid)};var result=await new EmployeeService(r).SaveAsync(null,Valid()with{LedgerAccount=account},default);Assert.False(result.Succeeded);Assert.Equal("LedgerAccount",result.Field);}
 [Fact]public async Task Valid_sap_account_is_accepted(){var r=new Repo{SapLedger=new(ExternalValidationStatus.Valid)};Assert.True((await new EmployeeService(r).SaveAsync(null,Valid()with{LedgerAccount="5000"},default)).Succeeded);}
 [Fact]public async Task Unavailable_sap_blocks_save_with_explicit_message(){var r=new Repo{SapLedger=new(ExternalValidationStatus.Unavailable)};var result=await new EmployeeService(r).SaveAsync(null,Valid()with{LedgerAccount="5000"},default);Assert.False(result.Succeeded);Assert.Contains("no está configurado o disponible",result.Error);}
 [Fact]public async Task Invalid_and_valid_sap_customers_have_functional_results(){var r=new Repo{SapCustomer=new(ExternalValidationStatus.Invalid)};Assert.False((await new EmployeeService(r).SaveAsync(null,Valid()with{Code="C1"},default)).Succeeded);r.SapCustomer=new(ExternalValidationStatus.Valid);Assert.True((await new EmployeeService(r).SaveAsync(null,Valid()with{Code="C1"},default)).Succeeded);}
 [Fact]public async Task Direct_request_cannot_update_inactive_employee(){var r=new Repo{Current=Employee(1)};var result=await new EmployeeService(r).SaveAsync("1",Valid(),default);Assert.False(result.Succeeded);Assert.False(r.Saved);}
 [Fact]public void Photo_validation_accepts_real_signatures_and_rejects_fake_content(){Assert.Null(EmployeePhotoValidation.Validate([0xFF,0xD8,0xFF,0x01]));Assert.Null(EmployeePhotoValidation.Validate([0x89,0x50,0x4E,0x47,0x0D,0x0A,0x1A,0x0A]));Assert.NotNull(EmployeePhotoValidation.Validate("not an image"u8.ToArray()));}
 [Fact]public async Task Photo_is_preserved_through_save_and_retrieval_contract(){var bytes=new byte[]{0xFF,0xD8,0xFF,0x01};var r=new Repo();var service=new EmployeeService(r);Assert.True((await service.SaveAsync(null,Valid()with{Photo=bytes},default)).Succeeded);Assert.Equal(bytes,await service.GetPhotoAsync("1",default));}
 [Fact]public async Task Photo_can_be_replaced(){var r=new Repo();var service=new EmployeeService(r);await service.SaveAsync(null,Valid()with{Photo=[0xFF,0xD8,0xFF,0x01]},default);await service.SaveAsync(null,Valid()with{Identification="2",Photo=[0x89,0x50,0x4E,0x47,0x0D,0x0A,0x1A,0x0A]},default);Assert.Equal("image/png",EmployeePhotoValidation.DetectContentType((await service.GetPhotoAsync("2",default))!));}
 [Fact]public void Calculates_tenure_with_completed_months_and_days()=>Assert.Equal((2,1,5),EmployeeService.CalculateTenure(new(2024,1,10),new(2026,2,15)));
 private static EmployeeInput Valid()=>new("1","","Empleado","TI",1000,new(2020,1,1),"0","","","","CR1","COL1","","Administrativo",0,0,0);
 private static Employee Employee(int status)=>new(1,"1","","Empleado","TI",1000,new(2020,1,1),status,"0","","","","CR1","COL1","","Administrativo",0,0,0,1,0,0);
 private sealed class Repo:IEmployeeRepository
 {private readonly Dictionary<string,byte[]>photos=[];public EmployeeDuplicate?Duplicate{get;set;}public Employee?Current{get;set;}public DateOnly?ReactivationDate{get;private set;}public ExternalValidationResult SapLedger{get;set;}=new(ExternalValidationStatus.Valid);public ExternalValidationResult SapCustomer{get;set;}=new(ExternalValidationStatus.Valid);public bool Saved{get;private set;}public ValueTask<IReadOnlyCollection<Employee>>ListAsync(string?s,bool i,CancellationToken t)=>ValueTask.FromResult<IReadOnlyCollection<Employee>>([]);public ValueTask<EmployeeFile?>GetAsync(string i,CancellationToken t)=>ValueTask.FromResult(Current is null?(EmployeeFile?)null:new(Current,[],[],[],[]));public ValueTask<byte[]?>GetPhotoAsync(string i,CancellationToken t)=>ValueTask.FromResult(photos.GetValueOrDefault(i));public ValueTask<EmployeeDuplicate?>FindDuplicateAsync(string i,string c,string?e,CancellationToken t)=>ValueTask.FromResult(Duplicate);public ValueTask<ExternalValidationResult>ValidateSapLedgerAccountAsync(string a,CancellationToken t)=>ValueTask.FromResult(SapLedger);public ValueTask<ExternalValidationResult>ValidateSapCustomerAsync(string c,CancellationToken t)=>ValueTask.FromResult(SapCustomer);public ValueTask<bool>CreateAsync(EmployeeInput i,CancellationToken t){Saved=true;if(i.Photo is not null)photos[i.Identification]=i.Photo;return ValueTask.FromResult(true);}public ValueTask<bool>UpdateAsync(string o,EmployeeInput i,CancellationToken t)=>CreateAsync(i,t);public ValueTask<bool>InactivateAsync(string i,CancellationToken t)=>ValueTask.FromResult(Current?.StatusCode==0);public ValueTask<bool>ReactivateAsync(string i,DateOnly d,CancellationToken t){if(Current?.StatusCode!=1)return ValueTask.FromResult(false);ReactivationDate=d;return ValueTask.FromResult(true);}}
}
