using System.Globalization;
using System.Text;
using Essco.Domain.HumanResources;
namespace Essco.Application.HumanResources;

public static class EmployeeCatalog
{
 public static readonly string[] Positions=["Administrador","Administrador Cuentas por Cobrar","Agente","Asistente Administrativo","Asistente Contable","Asistente Gerencia","Ayudante Bodega","Ayudante Chofer","Bodeguero","Chofer","Contador","Coordinador de Inventario","Facturador","Guarda","Jefe Bodega","Mercaderista","Micelaneo","Montacarguista","Promotor","Recepcionista","Supervisor","TI"];
 public static readonly string[] Categories=["Administrativo","Ventas","Reparto"];
}
public sealed record EmployeeValidationError(string Field,string Message);
public sealed record EmployeeInput(string Identification,string Code,string Name,string Position,decimal Salary,DateOnly HireDate,string Route,string Email,string Phone1,string Phone2,string BankAccount,string CollaboratorId,string LedgerAccount,string Category,decimal VacationEarned,decimal VacationUsed,decimal VacationPending,byte[]? Photo=null)
{
 public IReadOnlyCollection<EmployeeValidationError>Validate(){var e=new List<EmployeeValidationError>();if(string.IsNullOrWhiteSpace(Identification))e.Add(new(nameof(Identification),"La cédula es obligatoria."));if(string.IsNullOrWhiteSpace(Name))e.Add(new(nameof(Name),"El nombre es obligatorio."));if(!EmployeeCatalog.Positions.Contains(Position,StringComparer.OrdinalIgnoreCase))e.Add(new(nameof(Position),"Seleccione un puesto válido."));if(!EmployeeCatalog.Categories.Contains(Category,StringComparer.OrdinalIgnoreCase))e.Add(new(nameof(Category),"Seleccione una categoría válida."));if(HireDate==default)e.Add(new(nameof(HireDate),"La fecha de ingreso es obligatoria."));if(Salary<1000)e.Add(new(nameof(Salary),"Debe indicar un salario de al menos 1000."));if(string.IsNullOrWhiteSpace(BankAccount))e.Add(new(nameof(BankAccount),"La cuenta bancaria es obligatoria."));if(string.IsNullOrWhiteSpace(CollaboratorId))e.Add(new(nameof(CollaboratorId),"El ID del colaborador es obligatorio."));if(LedgerAccount.Length>15)e.Add(new(nameof(LedgerAccount),"La cuenta contable excede los 15 caracteres permitidos."));if(Code.Length>15)e.Add(new(nameof(Code),"El código de cliente excede los 15 caracteres permitidos."));if(Position.Equals("Agente",StringComparison.OrdinalIgnoreCase)&&string.IsNullOrWhiteSpace(Route))e.Add(new(nameof(Route),"La ruta es obligatoria para el puesto Agente."));if(VacationEarned<0||VacationUsed<0||VacationPending<0)e.Add(new("Vacation","Los valores de vacaciones no pueden ser negativos."));return e;}
}
public sealed record EmployeeSaveResult(bool Succeeded,string? Error=null,string? Field=null);
public sealed record EmployeeDuplicate(string Identification,string Code,int StatusCode);
public enum ExternalValidationStatus{Valid,Invalid,Unavailable}
public sealed record ExternalValidationResult(ExternalValidationStatus Status,string? Detail=null);
public interface IEmployeeRepository
{
 ValueTask<IReadOnlyCollection<Employee>>ListAsync(string?search,bool includeInactive,CancellationToken token);ValueTask<EmployeeFile?>GetAsync(string identification,CancellationToken token);ValueTask<byte[]?>GetPhotoAsync(string identification,CancellationToken token);ValueTask<EmployeeDuplicate?>FindDuplicateAsync(string identification,string code,string?excludingIdentification,CancellationToken token);ValueTask<ExternalValidationResult>ValidateSapLedgerAccountAsync(string account,CancellationToken token);ValueTask<ExternalValidationResult>ValidateSapCustomerAsync(string code,CancellationToken token);ValueTask<bool>CreateAsync(EmployeeInput input,CancellationToken token);ValueTask<bool>UpdateAsync(string originalIdentification,EmployeeInput input,CancellationToken token);ValueTask<bool>InactivateAsync(string identification,CancellationToken token);ValueTask<bool>ReactivateAsync(string identification,DateOnly newHireDate,CancellationToken token);
}
public sealed class EmployeeService(IEmployeeRepository repository)
{
 public ValueTask<IReadOnlyCollection<Employee>>ListAsync(string?s,bool i,CancellationToken t)=>repository.ListAsync(s?.Trim(),i,t);public ValueTask<EmployeeFile?>GetAsync(string id,CancellationToken t)=>repository.GetAsync(id.Trim(),t);public ValueTask<byte[]?>GetPhotoAsync(string id,CancellationToken t)=>repository.GetPhotoAsync(id.Trim(),t);
 public async ValueTask<EmployeeSaveResult>SaveAsync(string?original,EmployeeInput input,CancellationToken token){var x=input with{Identification=input.Identification.Trim(),Code=input.Code.Trim(),Name=NormalizeLegacyName(input.Name),Position=input.Position.Trim(),Route=input.Route.Trim(),Email=input.Email.Trim(),Phone1=input.Phone1.Trim(),Phone2=input.Phone2.Trim(),BankAccount=input.BankAccount.Trim(),CollaboratorId=input.CollaboratorId.Trim(),LedgerAccount=input.LedgerAccount.Trim(),Category=input.Category.Trim()};var error=x.Validate().FirstOrDefault();if(error is not null)return new(false,error.Message,error.Field);Employee? existing=null;if(!string.IsNullOrWhiteSpace(original)){var current=await repository.GetAsync(original,token);if(current is null)return new(false,"El empleado ya no existe.");existing=current.Employee;if(!existing.CanEdit)return new(false,$"El empleado está {existing.StatusName.ToUpperInvariant()} y no permite modificaciones.","Status");}var duplicate=await repository.FindDuplicateAsync(x.Identification,x.Code,original,token);if(duplicate is not null){var state=duplicate.StatusCode switch{0=>"ACTIVO",1=>"INACTIVO",2=>"CERRADO",3=>"LIQUIDADO",_=>$"EN ESTADO {duplicate.StatusCode}"};return new(false,$"El empleado ya existe y se encuentra {state}. No debe volver a crearse; búsquelo incluyendo empleados inactivos.",nameof(EmployeeInput.Identification));}var ledgerChanged=existing is null||!x.LedgerAccount.Equals(existing.LedgerAccount,StringComparison.OrdinalIgnoreCase);if(x.LedgerAccount.Length>0){var ledger=await repository.ValidateSapLedgerAccountAsync(x.LedgerAccount,token);if(ledger.Status==ExternalValidationStatus.Invalid)return new(false,"La cuenta contable no existe en el plan de cuentas de SAP.",nameof(EmployeeInput.LedgerAccount));if(ledger.Status==ExternalValidationStatus.Unavailable&&ledgerChanged)return new(false,$"No fue posible validar la cuenta contable porque SAP no está configurado o disponible ({ledger.Detail??"sin detalle"}). No se guardó el empleado.",nameof(EmployeeInput.LedgerAccount));}var customerChanged=existing is null||!x.Code.Equals(existing.Code,StringComparison.OrdinalIgnoreCase);if(x.Code.Length>0){var customer=await repository.ValidateSapCustomerAsync(x.Code,token);if(customer.Status==ExternalValidationStatus.Invalid)return new(false,"El código de cliente no existe en SAP.",nameof(EmployeeInput.Code));if(customer.Status==ExternalValidationStatus.Unavailable&&customerChanged)return new(false,$"No fue posible validar el código de cliente porque SAP no está configurado o disponible ({customer.Detail??"sin detalle"}). No se guardó el empleado.",nameof(EmployeeInput.Code));}var saved=string.IsNullOrWhiteSpace(original)?await repository.CreateAsync(x,token):await repository.UpdateAsync(original,x,token);return new(saved,saved?null:"No fue posible guardar el empleado.");}
 public async ValueTask<EmployeeSaveResult>InactivateAsync(string identification,CancellationToken token){if(string.IsNullOrWhiteSpace(identification))return new(false,"Debe seleccionar un empleado.");var file=await repository.GetAsync(identification.Trim(),token);if(file is null)return new(false,"El empleado no existe.");if(!file.Employee.CanInactivate)return new(false,$"Solo un empleado ACTIVO puede inactivarse. Estado actual: {file.Employee.StatusName.ToUpperInvariant()}.");var saved=await repository.InactivateAsync(identification.Trim(),token);return new(saved,saved?null:"El estado cambió antes de completar la operación. Actualice la página.");}
 public async ValueTask<EmployeeSaveResult>ReactivateAsync(string identification,DateOnly newHireDate,CancellationToken token){if(string.IsNullOrWhiteSpace(identification))return new(false,"Debe seleccionar un empleado.");if(newHireDate==default)return new(false,"La nueva fecha de ingreso es obligatoria.","ReactivationDate");if(newHireDate>DateOnly.FromDateTime(DateTime.Today))return new(false,"La fecha de ingreso no puede estar en el futuro.","ReactivationDate");var file=await repository.GetAsync(identification.Trim(),token);if(file is null)return new(false,"El empleado no existe.");if(file.Employee.StatusCode!=1)return new(false,$"Solo un empleado INACTIVO puede reactivarse. Estado actual: {file.Employee.StatusName.ToUpperInvariant()}.");var saved=await repository.ReactivateAsync(identification.Trim(),newHireDate,token);return new(saved,saved?null:"El estado cambió antes de completar la reactivación. Actualice la página.");}
 public static(int Years,int Months,int Days)CalculateTenure(DateOnly hireDate,DateOnly today){if(hireDate>today)return(0,0,0);var years=today.Year-hireDate.Year;var months=today.Month-hireDate.Month;var days=today.Day-hireDate.Day;if(days<0){months--;var previous=today.AddMonths(-1);days+=DateTime.DaysInMonth(previous.Year,previous.Month);}if(months<0){years--;months+=12;}return(years,months,days);}
 internal static string NormalizeLegacyName(string value){var source=value.Trim().Normalize(NormalizationForm.FormD);var result=new StringBuilder(source.Length);foreach(var c in source){var category=CharUnicodeInfo.GetUnicodeCategory(c);if(category!=UnicodeCategory.NonSpacingMark&&(char.IsLetterOrDigit(c)||char.IsWhiteSpace(c)))result.Append(c);}return result.ToString().Normalize(NormalizationForm.FormC);}
}
public static class EmployeePhotoValidation
{
 public const int MaxBytes=5*1024*1024;
 public static string?Validate(byte[] data){if(data.Length==0)return"Seleccione una fotografía.";if(data.Length>MaxBytes)return"La fotografía no puede superar 5 MB.";return DetectContentType(data) is null?"El contenido no corresponde a una imagen JPG, PNG o WEBP válida.":null;}
 public static string?DetectContentType(byte[] data){if(data.Length>=3&&data[0]==0xFF&&data[1]==0xD8&&data[2]==0xFF)return"image/jpeg";if(data.Length>=8&&data[0]==0x89&&data[1]==0x50&&data[2]==0x4E&&data[3]==0x47&&data[4]==0x0D&&data[5]==0x0A&&data[6]==0x1A&&data[7]==0x0A)return"image/png";if(data.Length>=12&&Encoding.ASCII.GetString(data,0,4)=="RIFF"&&Encoding.ASCII.GetString(data,8,4)=="WEBP")return"image/webp";return null;}
}
