using System.Globalization;
using System.Text;
using Essco.Domain.HumanResources;
namespace Essco.Application.HumanResources;

public static class EmployeeCatalog
{
 public static readonly string[] Positions=["Administrador","Administrador Cuentas por Cobrar","Agente","Asistente Administrativo","Asistente Contable","Asistente Gerencia","Ayudante Bodega","Ayudante Chofer","Bodeguero","Chofer","Contador","Coordinador de Inventario","Facturador","Guarda","Jefe Bodega","Mercaderista","Micelaneo","Montacarguista","Promotor","Recepcionista","Supervisor","TI"];
 public static readonly string[] Categories=["Administrativo","Ventas","Reparto"];
}
public sealed record EmployeeInput(string Identification,string Code,string Name,string Position,decimal Salary,DateOnly HireDate,bool Active,string Route,string Email,string Phone1,string Phone2,string BankAccount,string CollaboratorId,string LedgerAccount,string Category,decimal VacationEarned,decimal VacationUsed,decimal VacationPending,byte[]? Photo=null)
{
 public IReadOnlyCollection<string>Validate(){var e=new List<string>();if(string.IsNullOrWhiteSpace(Identification))e.Add("La cédula es obligatoria.");if(string.IsNullOrWhiteSpace(Name))e.Add("El nombre es obligatorio.");if(!EmployeeCatalog.Positions.Contains(Position,StringComparer.OrdinalIgnoreCase))e.Add("Seleccione un puesto válido.");if(!EmployeeCatalog.Categories.Contains(Category,StringComparer.OrdinalIgnoreCase))e.Add("Seleccione una categoría válida.");if(HireDate==default)e.Add("La fecha de ingreso es obligatoria.");if(Salary<1000)e.Add("Debe indicar un salario de al menos 1000.");if(string.IsNullOrWhiteSpace(BankAccount))e.Add("La cuenta bancaria es obligatoria.");if(string.IsNullOrWhiteSpace(CollaboratorId))e.Add("El ID del colaborador es obligatorio.");if(LedgerAccount.Length>15)e.Add("La cuenta contable excede los 15 caracteres permitidos.");if(Code.Length>15)e.Add("El código de cliente excede los 15 caracteres permitidos.");if(Position.Equals("Agente",StringComparison.OrdinalIgnoreCase)&&string.IsNullOrWhiteSpace(Route))e.Add("La ruta es obligatoria para el puesto Agente.");if(VacationEarned<0||VacationUsed<0||VacationPending<0)e.Add("Los valores de vacaciones no pueden ser negativos.");return e;}
}
public sealed record EmployeeSaveResult(bool Succeeded,string? Error=null);
public interface IEmployeeRepository
{
 ValueTask<IReadOnlyCollection<Employee>>ListAsync(string?search,bool includeInactive,CancellationToken token);ValueTask<EmployeeFile?>GetAsync(string identification,CancellationToken token);ValueTask<byte[]?>GetPhotoAsync(string identification,CancellationToken token);ValueTask<bool>ExistsAsync(string identification,string code,string?excludingIdentification,CancellationToken token);ValueTask<bool>SapLedgerAccountExistsAsync(string account,CancellationToken token);ValueTask<bool>SapCustomerExistsAsync(string code,CancellationToken token);ValueTask<bool>CreateAsync(EmployeeInput input,CancellationToken token);ValueTask<bool>UpdateAsync(string originalIdentification,EmployeeInput input,CancellationToken token);ValueTask<bool>SetActiveAsync(string identification,bool active,CancellationToken token);
}
public sealed class EmployeeService(IEmployeeRepository repository)
{
 public ValueTask<IReadOnlyCollection<Employee>>ListAsync(string?s,bool i,CancellationToken t)=>repository.ListAsync(s?.Trim(),i,t);public ValueTask<EmployeeFile?>GetAsync(string id,CancellationToken t)=>repository.GetAsync(id.Trim(),t);public ValueTask<byte[]?>GetPhotoAsync(string id,CancellationToken t)=>repository.GetPhotoAsync(id.Trim(),t);
 public async ValueTask<EmployeeSaveResult>SaveAsync(string?original,EmployeeInput input,CancellationToken token){var x=input with{Identification=input.Identification.Trim(),Code=input.Code.Trim(),Name=NormalizeLegacyName(input.Name),Position=input.Position.Trim(),Route=input.Route.Trim(),Email=input.Email.Trim(),Phone1=input.Phone1.Trim(),Phone2=input.Phone2.Trim(),BankAccount=input.BankAccount.Trim(),CollaboratorId=input.CollaboratorId.Trim(),LedgerAccount=input.LedgerAccount.Trim(),Category=input.Category.Trim()};var error=x.Validate().FirstOrDefault();if(error is not null)return new(false,error);if(await repository.ExistsAsync(x.Identification,x.Code,original,token))return new(false,"Ya existe otro empleado con la misma cédula o código.");if(x.LedgerAccount.Length>0&&!await repository.SapLedgerAccountExistsAsync(x.LedgerAccount,token))return new(false,"Debe indicar una cuenta contable que exista en el plan de cuentas de SAP.");if(x.Code.Length>0&&!await repository.SapCustomerExistsAsync(x.Code,token))return new(false,"Debe indicar un código de cliente que exista en SAP.");var saved=string.IsNullOrWhiteSpace(original)?await repository.CreateAsync(x,token):await repository.UpdateAsync(original,x,token);return new(saved,saved?null:"No fue posible guardar el empleado.");}
 public async ValueTask<EmployeeSaveResult>SetActiveAsync(string identification,bool active,CancellationToken token){if(string.IsNullOrWhiteSpace(identification))return new(false,"Debe seleccionar un empleado.");var saved=await repository.SetActiveAsync(identification.Trim(),active,token);return new(saved,saved?null:"No fue posible cambiar el estado del empleado.");}
 public static(int Years,int Months,int Days)CalculateTenure(DateOnly hireDate,DateOnly today){if(hireDate>today)return(0,0,0);var years=today.Year-hireDate.Year;var months=today.Month-hireDate.Month;var days=today.Day-hireDate.Day;if(days<0){months--;var previous=today.AddMonths(-1);days+=DateTime.DaysInMonth(previous.Year,previous.Month);}if(months<0){years--;months+=12;}return(years,months,days);}
 internal static string NormalizeLegacyName(string value){var source=value.Trim().Normalize(NormalizationForm.FormD);var result=new StringBuilder(source.Length);foreach(var c in source){var category=CharUnicodeInfo.GetUnicodeCategory(c);if(category!=UnicodeCategory.NonSpacingMark&&(char.IsLetterOrDigit(c)||char.IsWhiteSpace(c)))result.Append(c);}return result.ToString().Normalize(NormalizationForm.FormC);}
}
